//! Brim ears point data structures for automatic brim generation
//!
//! C++ Reference:
//! - BrimEarsPoint.hpp
//!
//! This module provides data structures for tracking support points used in
//! automatic brim ear generation. These points define where brim "ears" should
//! be placed to improve bed adhesion for small or problematic parts.

use nalgebra::{Transform3, Vector3};

/// Status of support point generation
/// BrimEarsPoint.hpp:9-15
/// C++: enum class PointsStatus
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PointsStatus {
    // No points were generated so far
    // BrimEarsPoint.hpp:10
    // C++: NoPoints,
    NoPoints,

    // The autogeneration algorithm triggered, but not yet finished
    // BrimEarsPoint.hpp:11
    // C++: Generating,
    Generating,

    // Points were autogenerated (i.e. copied from the backend)
    // BrimEarsPoint.hpp:12
    // C++: AutoGenerated,
    AutoGenerated,

    // User has done some edits
    // BrimEarsPoint.hpp:13
    // C++: UserModified
    UserModified,
}

/// A support point for brim ear generation
/// BrimEarsPoint.hpp:17-63
/// C++: struct BrimPoint
#[derive(Debug, Clone, PartialEq)]
pub struct BrimPoint {
    // 3D position of the support point
    // BrimEarsPoint.hpp:19
    // C++: Vec3f pos;
    pub pos: Vector3<f32>,

    // Radius of the brim ear head at this point
    // BrimEarsPoint.hpp:20
    // C++: float head_front_radius;
    pub head_front_radius: f32,

    // Index of the volume this point belongs to (-1 for none)
    // BrimEarsPoint.hpp:21
    // C++: int volume_idx;
    pub volume_idx: i32,
}

impl BrimPoint {
    // Create a new BrimPoint with zero position
    // BrimEarsPoint.hpp:23-26
    // C++: BrimPoint() : pos(Vec3f::Zero()), head_front_radius(0.f), volume_idx(-1) {}
    pub fn new() -> Self {
        BrimPoint {
            pos: Vector3::zeros(),
            head_front_radius: 0.0,
            volume_idx: -1,
        }
    }

    // Create a BrimPoint from individual coordinates
    // BrimEarsPoint.hpp:28-35
    // C++: BrimPoint(float pos_x, float pos_y, float pos_z, float head_radius, int volume_idx = -1)
    pub fn from_coords(
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        head_radius: f32,
        volume_idx: i32,
    ) -> Self {
        BrimPoint {
            pos: Vector3::new(pos_x, pos_y, pos_z),
            head_front_radius: head_radius,
            volume_idx,
        }
    }

    // Create a BrimPoint from a position vector
    // BrimEarsPoint.hpp:37-42
    // C++: BrimPoint(Vec3f position, float head_radius, int volume_idx = -1)
    pub fn from_position(position: Vector3<f32>, head_radius: f32, volume_idx: i32) -> Self {
        BrimPoint {
            pos: position,
            head_front_radius: head_radius,
            volume_idx,
        }
    }

    // Transform the point by a transformation matrix and return new position
    // BrimEarsPoint.hpp:44-48
    // C++: Vec3f transform(const Transform3d &trsf)
    pub fn transform(&self, transform: &Transform3<f64>) -> Vector3<f32> {
        // Convert to f64, apply transform, convert back to f32
        // BrimEarsPoint.hpp:46
        // C++: Vec3d result = trsf * pos.cast<double>();
        let pos_f64 = self.pos.cast::<f64>();
        let transformed = transform.transform_point(&nalgebra::Point3::from(pos_f64));

        // Return as f32
        // BrimEarsPoint.hpp:47
        // C++: return result.cast<float>();
        transformed.coords.cast::<f32>()
    }

    // Apply transformation to this point in-place
    // BrimEarsPoint.hpp:50-53
    // C++: void set_transform(const Transform3d& trsf)
    pub fn set_transform(&mut self, transform: &Transform3<f64>) {
        // BrimEarsPoint.hpp:52
        // C++: pos = transform(trsf);
        self.pos = self.transform(transform);
    }

    // Check if two BrimPoints are approximately equal
    // BrimEarsPoint.hpp:55-59
    // C++: bool operator==(const BrimPoint &sp) const
    pub fn approx_eq(&self, other: &BrimPoint) -> bool {
        // BrimEarsPoint.hpp:57
        // C++: float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        let rdiff = (self.head_front_radius - other.head_front_radius).abs();

        // BrimEarsPoint.hpp:58
        // C++: return (pos == sp.pos) && rdiff < float(EPSILON);
        const EPSILON: f32 = 1e-6;
        self.pos == other.pos && rdiff < EPSILON
    }
}

impl Default for BrimPoint {
    fn default() -> Self {
        Self::new()
    }
}

impl Eq for BrimPoint {}

impl std::hash::Hash for BrimPoint {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        // Hash the position components as bits
        self.pos.x.to_bits().hash(state);
        self.pos.y.to_bits().hash(state);
        self.pos.z.to_bits().hash(state);
        self.head_front_radius.to_bits().hash(state);
        self.volume_idx.hash(state);
    }
}

/// Collection of brim points
/// BrimEarsPoint.hpp:65
/// C++: using BrimPoints = std::vector<BrimPoint>;
pub type BrimPoints = Vec<BrimPoint>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new() {
        let point = BrimPoint::new();
        assert_eq!(point.pos, Vector3::zeros());
        assert_eq!(point.head_front_radius, 0.0);
        assert_eq!(point.volume_idx, -1);
    }

    #[test]
    fn test_from_coords() {
        let point = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        assert_eq!(point.pos, Vector3::new(1.0, 2.0, 3.0));
        assert_eq!(point.head_front_radius, 5.0);
        assert_eq!(point.volume_idx, 10);
    }

    #[test]
    fn test_from_position() {
        let pos = Vector3::new(1.0, 2.0, 3.0);
        let point = BrimPoint::from_position(pos, 5.0, 10);
        assert_eq!(point.pos, pos);
        assert_eq!(point.head_front_radius, 5.0);
        assert_eq!(point.volume_idx, 10);
    }

    #[test]
    fn test_default_volume_idx() {
        let point = BrimPoint::from_coords(0.0, 0.0, 0.0, 1.0, -1);
        assert_eq!(point.volume_idx, -1);
    }

    #[test]
    fn test_transform() {
        let point = BrimPoint::from_coords(1.0, 0.0, 0.0, 1.0, -1);

        // Create a translation transform (move by (2, 3, 4))
        let mut transform = Transform3::<f64>::identity();
        transform.append_translation_mut(&nalgebra::Vector3::new(2.0, 3.0, 4.0));

        let transformed_pos = point.transform(&transform);

        // Original (1, 0, 0) + translation (2, 3, 4) = (3, 3, 4)
        assert!((transformed_pos.x - 3.0).abs() < 1e-5);
        assert!((transformed_pos.y - 3.0).abs() < 1e-5);
        assert!((transformed_pos.z - 4.0).abs() < 1e-5);
    }

    #[test]
    fn test_set_transform() {
        let mut point = BrimPoint::from_coords(1.0, 0.0, 0.0, 1.0, -1);

        // Create a translation transform
        let mut transform = Transform3::<f64>::identity();
        transform.append_translation_mut(&nalgebra::Vector3::new(2.0, 3.0, 4.0));

        point.set_transform(&transform);

        // Check that position was updated in-place
        assert!((point.pos.x - 3.0).abs() < 1e-5);
        assert!((point.pos.y - 3.0).abs() < 1e-5);
        assert!((point.pos.z - 4.0).abs() < 1e-5);
    }

    #[test]
    fn test_approx_eq() {
        let point1 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point2 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point3 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.1, 10);
        let point4 = BrimPoint::from_coords(1.1, 2.0, 3.0, 5.0, 10);

        assert!(point1.approx_eq(&point2));
        assert!(!point1.approx_eq(&point3)); // Different radius
        assert!(!point1.approx_eq(&point4)); // Different position
    }

    #[test]
    fn test_approx_eq_epsilon() {
        let point1 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point2 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0 + 1e-7, 10);

        // Radius difference is very small (< EPSILON)
        assert!(point1.approx_eq(&point2));
    }

    #[test]
    fn test_points_status_variants() {
        assert_eq!(PointsStatus::NoPoints, PointsStatus::NoPoints);
        assert_ne!(PointsStatus::NoPoints, PointsStatus::Generating);
        assert_ne!(PointsStatus::AutoGenerated, PointsStatus::UserModified);
    }

    #[test]
    fn test_default() {
        let point1 = BrimPoint::new();
        let point2 = BrimPoint::default();
        assert!(point1.approx_eq(&point2));
    }

    #[test]
    fn test_clone() {
        let point1 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point2 = point1.clone();
        assert!(point1.approx_eq(&point2));
    }

    #[test]
    fn test_brim_points_collection() {
        let mut points: BrimPoints = Vec::new();
        points.push(BrimPoint::from_coords(0.0, 0.0, 0.0, 1.0, 0));
        points.push(BrimPoint::from_coords(1.0, 1.0, 1.0, 2.0, 1));

        assert_eq!(points.len(), 2);
        assert_eq!(points[0].volume_idx, 0);
        assert_eq!(points[1].volume_idx, 1);
    }
}
