//! Faithful port of SLA/SupportPoint.hpp (header-only).
//!
//! C++ Reference:
//! - SLA/SupportPoint.hpp
//!
//! C++ `Vec3f` maps to the crate's `Vec3f` (nalgebra `Vector3<f32>`, mirroring
//! Eigen `Matrix<float,3,1>`); `EPSILON` is `crate::libslic3r::EPSILON` (1e-4).

use crate::libslic3r::EPSILON;
use crate::triangle_mesh::Vec3f;
use serde::{Deserialize, Serialize};

// SupportPoint.hpp:8 — An enum to keep track of where the current points on the ModelObject came from.
// SupportPoint.hpp:9
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PointsStatus {
    NoPoints,      // No points were generated so far. (SupportPoint.hpp:10)
    Generating,    // The autogeneration algorithm triggered, but not yet finished. (SupportPoint.hpp:11)
    AutoGenerated, // Points were autogenerated (i.e. copied from the backend). (SupportPoint.hpp:12)
    UserModified,  // User has done some edits. (SupportPoint.hpp:13)
}

/// serde adapter for `Vec3f` (nalgebra is built without its `serde` feature here):
/// (de)serializes the position as `[f32; 3]`, matching the cereal layout of
/// `ar(pos, ...)` in SupportPoint.hpp:59.
mod vec3f_serde {
    use super::Vec3f;
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S: Serializer>(v: &Vec3f, s: S) -> Result<S::Ok, S::Error> {
        [v.x, v.y, v.z].serialize(s)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec3f, D::Error> {
        let a = <[f32; 3]>::deserialize(d)?;
        Ok(Vec3f::new(a[0], a[1], a[2]))
    }
}

// SupportPoint.hpp:16
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct SupportPoint {
    #[serde(with = "vec3f_serde")]
    pub pos: Vec3f,             // SupportPoint.hpp:18
    pub head_front_radius: f32, // SupportPoint.hpp:19
    pub is_new_island: bool,    // SupportPoint.hpp:20
}

impl SupportPoint {
    // SupportPoint.hpp:22
    // SupportPoint()
    //     : pos(Vec3f::Zero()), head_front_radius(0.f), is_new_island(false)
    pub fn new() -> Self {
        Self {
            pos: Vec3f::zeros(),
            head_front_radius: 0.0,
            is_new_island: false,
        }
    }

    // SupportPoint.hpp:26
    // SupportPoint(float pos_x, float pos_y, float pos_z, float head_radius,
    //              bool new_island = false)
    pub fn from_coords(pos_x: f32, pos_y: f32, pos_z: f32, head_radius: f32, new_island: bool) -> Self {
        Self {
            pos: Vec3f::new(pos_x, pos_y, pos_z),
            head_front_radius: head_radius,
            is_new_island: new_island,
        }
    }

    // SupportPoint.hpp:36
    // SupportPoint(Vec3f position, float head_radius, bool new_island = false)
    pub fn from_position(position: Vec3f, head_radius: f32, new_island: bool) -> Self {
        Self {
            pos: position,
            head_front_radius: head_radius,
            is_new_island: new_island,
        }
    }

    // SupportPoint.hpp:42
    // SupportPoint(Eigen::Matrix<float, 5, 1, Eigen::DontAlign> data)
    //     : pos(data(0), data(1), data(2))
    //     , head_front_radius(data(3))
    //     , is_new_island(data(4) != 0.f)
    pub fn from_data(data: [f32; 5]) -> Self {
        Self {
            pos: Vec3f::new(data[0], data[1], data[2]),
            head_front_radius: data[3],
            is_new_island: data[4] != 0.0,
        }
    }
}

impl Default for SupportPoint {
    // SupportPoint.hpp:22 — default constructor.
    fn default() -> Self {
        Self::new()
    }
}

impl PartialEq for SupportPoint {
    // SupportPoint.hpp:48
    // bool operator==(const SupportPoint &sp) const
    fn eq(&self, sp: &Self) -> bool {
        // SupportPoint.hpp:50
        let rdiff = (self.head_front_radius - sp.head_front_radius).abs();
        // SupportPoint.hpp:51-52
        (self.pos == sp.pos) && rdiff < EPSILON as f32 && self.is_new_island == sp.is_new_island
    }
}

// SupportPoint.hpp:55 — operator!= is derived from operator== (PartialEq provides `ne`).

// SupportPoint.hpp:57-60 — template<class Archive> void serialize(Archive &ar)
// { ar(pos, head_front_radius, is_new_island); }
// Covered by the serde Serialize/Deserialize derives above (field order matches).

// SupportPoint.hpp:63
pub type SupportPoints = Vec<SupportPoint>;
