//! Brim ears point data structures for automatic brim generation
//!
//! C++ Reference:
//! - BrimEarsPoint.hpp
//!
//! 1:1 line-by-line port of `BrimEarsPoint.hpp`. This header-only file defines
//! the `PointsStatus` enum, the `BrimPoint` struct, and the `BrimPoints` alias.

// BrimEarsPoint.hpp:4
// C++: #include <libslic3r/Point.hpp>
// coord_t->i64, coordf_t->f64. Vec3f == Eigen::Matrix<float,3,1>, Vec3d ==
// Eigen::Matrix<double,3,1>, Transform3d == Eigen::Transform<double,3,Affine>.
use crate::libslic3r::EPSILON;
use nalgebra::{Transform3, Vector3};

// BrimEarsPoint.hpp:7
// C++: namespace Slic3r {

// An enum to keep track of where the current points on the ModelObject came from.
// BrimEarsPoint.hpp:9
/// BrimEarsPoint.hpp:10-15
/// C++: enum class PointsStatus
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PointsStatus {
    // No points were generated so far.
    // BrimEarsPoint.hpp:11
    // C++: NoPoints,
    NoPoints,

    // The autogeneration algorithm triggered, but not yet finished.
    // BrimEarsPoint.hpp:12
    // C++: Generating,
    Generating,

    // Points were autogenerated (i.e. copied from the backend).
    // BrimEarsPoint.hpp:13
    // C++: AutoGenerated,
    AutoGenerated,

    // User has done some edits.
    // BrimEarsPoint.hpp:14
    // C++: UserModified
    UserModified,
}

/// BrimEarsPoint.hpp:17-65
/// C++: struct BrimPoint
#[derive(Debug, Clone)]
pub struct BrimPoint {
    // BrimEarsPoint.hpp:19
    // C++: Vec3f pos;
    pub pos: Vector3<f32>,

    // BrimEarsPoint.hpp:20
    // C++: float head_front_radius;
    pub head_front_radius: f32,

    // BrimEarsPoint.hpp:21
    // C++: int volume_idx;
    pub volume_idx: i32,
}

impl BrimPoint {
    // BrimEarsPoint.hpp:23-25
    // C++: BrimPoint()
    //          : pos(Vec3f::Zero()), head_front_radius(0.f), volume_idx(-1)
    //      {}
    pub fn new() -> Self {
        BrimPoint {
            pos: Vector3::zeros(),
            head_front_radius: 0.0,
            volume_idx: -1,
        }
    }

    // BrimEarsPoint.hpp:27-35
    // C++: BrimPoint(float pos_x,
    //               float pos_y,
    //               float pos_z,
    //               float head_radius,
    //               int volume_idx = -1)
    //          : pos(pos_x, pos_y, pos_z)
    //          , head_front_radius(head_radius)
    //          , volume_idx(volume_idx)
    //      {}
    pub fn from_coords(
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        head_radius: f32,
        volume_idx: i32,
    ) -> Self {
        BrimPoint {
            pos: Vector3::new(pos_x, pos_y, pos_z),
            head_front_radius: head_radius,
            volume_idx,
        }
    }

    // BrimEarsPoint.hpp:37-41
    // C++: BrimPoint(Vec3f position, float head_radius, int volume_idx = -1)
    //          : pos(position)
    //          , head_front_radius(head_radius)
    //          , volume_idx(volume_idx)
    //      {}
    pub fn from_position(position: Vector3<f32>, head_radius: f32, volume_idx: i32) -> Self {
        BrimPoint {
            pos: position,
            head_front_radius: head_radius,
            volume_idx,
        }
    }

    // BrimEarsPoint.hpp:43-47
    // C++: Vec3f transform(const Transform3d &trsf)
    pub fn transform(&self, trsf: &Transform3<f64>) -> Vector3<f32> {
        // BrimEarsPoint.hpp:45
        // C++: Vec3d result = trsf * pos.cast<double>();
        let result = trsf.transform_point(&nalgebra::Point3::from(self.pos.cast::<f64>()));

        // BrimEarsPoint.hpp:46
        // C++: return result.cast<float>();
        result.coords.cast::<f32>()
    }

    // BrimEarsPoint.hpp:49-52
    // C++: void set_transform(const Transform3d& trsf)
    pub fn set_transform(&mut self, trsf: &Transform3<f64>) {
        // BrimEarsPoint.hpp:51
        // C++: pos = transform(trsf);
        self.pos = self.transform(trsf);
    }

    // BrimEarsPoint.hpp:61-64
    // C++: template<class Archive> void serialize(Archive &ar)
    //      {
    //          ar(pos, head_front_radius, volume_idx);
    //      }
    //
    // The cereal serialization template is not ported: it requires the cereal
    // archive machinery which is not present in the Rust crate (no native dep
    // is added per porting rules). The serialized field order is
    // (pos, head_front_radius, volume_idx).
}

// BrimEarsPoint.hpp:54-60
// C++: bool operator==(const BrimPoint &sp) const
//      {
//          float rdiff = std::abs(head_front_radius - sp.head_front_radius);
//          return (pos == sp.pos) && rdiff < float(EPSILON);
//      }
//      bool operator!=(const BrimPoint &sp) const { return !(sp == (*this)); }
//
// Note: PartialEq here mirrors the C++ approximate equality operator exactly,
// so `==` / `!=` in Rust match `operator==` / `operator!=` in C++. Because this
// comparison is approximate (not strict), `Eq`/`Hash` are intentionally NOT
// implemented (the C++ struct has neither).
impl PartialEq for BrimPoint {
    fn eq(&self, sp: &BrimPoint) -> bool {
        // BrimEarsPoint.hpp:56
        // C++: float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        let rdiff = (self.head_front_radius - sp.head_front_radius).abs();

        // BrimEarsPoint.hpp:57
        // C++: return (pos == sp.pos) && rdiff < float(EPSILON);
        self.pos == sp.pos && rdiff < EPSILON as f32
    }
}

impl Default for BrimPoint {
    fn default() -> Self {
        Self::new()
    }
}

/// BrimEarsPoint.hpp:67
/// C++: using BrimPoints = std::vector<BrimPoint>;
pub type BrimPoints = Vec<BrimPoint>;

// BrimEarsPoint.hpp:69
// C++: }  (namespace Slic3r)

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new() {
        let point = BrimPoint::new();
        assert_eq!(point.pos, Vector3::zeros());
        assert_eq!(point.head_front_radius, 0.0);
        assert_eq!(point.volume_idx, -1);
    }

    #[test]
    fn test_from_coords() {
        let point = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        assert_eq!(point.pos, Vector3::new(1.0, 2.0, 3.0));
        assert_eq!(point.head_front_radius, 5.0);
        assert_eq!(point.volume_idx, 10);
    }

    #[test]
    fn test_from_position() {
        let pos = Vector3::new(1.0, 2.0, 3.0);
        let point = BrimPoint::from_position(pos, 5.0, 10);
        assert_eq!(point.pos, pos);
        assert_eq!(point.head_front_radius, 5.0);
        assert_eq!(point.volume_idx, 10);
    }

    #[test]
    fn test_default_volume_idx() {
        let point = BrimPoint::from_coords(0.0, 0.0, 0.0, 1.0, -1);
        assert_eq!(point.volume_idx, -1);
    }

    #[test]
    fn test_transform() {
        let point = BrimPoint::from_coords(1.0, 0.0, 0.0, 1.0, -1);

        // Create a translation transform (move by (2, 3, 4))
        let mut transform = Transform3::<f64>::identity();
        transform.append_translation_mut(&nalgebra::Vector3::new(2.0, 3.0, 4.0));

        let transformed_pos = point.transform(&transform);

        // Original (1, 0, 0) + translation (2, 3, 4) = (3, 3, 4)
        assert!((transformed_pos.x - 3.0).abs() < 1e-5);
        assert!((transformed_pos.y - 3.0).abs() < 1e-5);
        assert!((transformed_pos.z - 4.0).abs() < 1e-5);
    }

    #[test]
    fn test_set_transform() {
        let mut point = BrimPoint::from_coords(1.0, 0.0, 0.0, 1.0, -1);

        // Create a translation transform
        let mut transform = Transform3::<f64>::identity();
        transform.append_translation_mut(&nalgebra::Vector3::new(2.0, 3.0, 4.0));

        point.set_transform(&transform);

        // Check that position was updated in-place
        assert!((point.pos.x - 3.0).abs() < 1e-5);
        assert!((point.pos.y - 3.0).abs() < 1e-5);
        assert!((point.pos.z - 4.0).abs() < 1e-5);
    }

    #[test]
    fn test_eq() {
        let point1 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point2 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point3 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.1, 10);
        let point4 = BrimPoint::from_coords(1.1, 2.0, 3.0, 5.0, 10);

        assert!(point1 == point2);
        assert!(point1 != point3); // Different radius
        assert!(point1 != point4); // Different position
    }

    #[test]
    fn test_eq_epsilon() {
        // Radius difference < float(EPSILON) == 1e-4 -> equal.
        let point1 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point2 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0 + 1e-5, 10);
        assert!(point1 == point2);

        // Radius difference > float(EPSILON) -> not equal.
        let point3 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0 + 1e-3, 10);
        assert!(point1 != point3);
    }

    #[test]
    fn test_points_status_variants() {
        assert_eq!(PointsStatus::NoPoints, PointsStatus::NoPoints);
        assert_ne!(PointsStatus::NoPoints, PointsStatus::Generating);
        assert_ne!(PointsStatus::AutoGenerated, PointsStatus::UserModified);
    }

    #[test]
    fn test_default() {
        let point1 = BrimPoint::new();
        let point2 = BrimPoint::default();
        assert!(point1 == point2);
    }

    #[test]
    fn test_clone() {
        let point1 = BrimPoint::from_coords(1.0, 2.0, 3.0, 5.0, 10);
        let point2 = point1.clone();
        assert!(point1 == point2);
    }

    #[test]
    fn test_brim_points_collection() {
        let mut points: BrimPoints = Vec::new();
        points.push(BrimPoint::from_coords(0.0, 0.0, 0.0, 1.0, 0));
        points.push(BrimPoint::from_coords(1.0, 1.0, 1.0, 2.0, 1));

        assert_eq!(points.len(), 2);
        assert_eq!(points[0].volume_idx, 0);
        assert_eq!(points[1].volume_idx, 1);
    }
}
