//! Polygon tessellation into triangles.
//!
//! 1:1 port of `Tesselate.cpp` / `Tesselate.hpp`.
//!
//! The C++ implementation uses the native GLU tessellation library
//! (`glu-libtess`, SGI libtess) via the `GluTessWrapper` class. GLU calls back
//! into the wrapper with a stream of OpenGL primitives (`GL_TRIANGLES`,
//! `GL_TRIANGLE_FAN`, `GL_TRIANGLE_STRIP`), and the wrapper's `tessVertex`
//! callback converts that primitive stream into a flat list of output
//! triangles (3 consecutive vertices = 1 triangle), honoring the `m_flipped`
//! winding flag.
//!
//! `glu-libtess` is a native C dependency and is NOT wasm-safe, so it cannot be
//! linked here. Instead the polygon-with-holes is triangulated with the
//! pure-Rust `earcutr` (MapBox earcut) crate, and the resulting triangles are
//! fed through a faithful 1:1 port of the `GluTessWrapper::tessVertex` state
//! machine as `GL_TRIANGLES` primitives. This keeps the wrapper logic (winding,
//! flip, Z assignment, unscaling) byte-identical to C++; the only divergence is
//! the underlying triangulation backend (earcut vs SGI GLU), which can produce
//! a different triangle decomposition for the same region. See `divergences`.
//!
//! C++ Reference:
//! - Tesselate.hpp (25 lines)
//! - Tesselate.cpp (248 lines)

use crate::geometry::{ExPolygon, ExPolygons, Polygon};
use crate::unscale;
use crate::Result;

/// 3D vector for tessellated triangle vertices.
/// Mirrors C++ `Vec3d` (and `Pointf3s = std::vector<Vec3d>`).
/// Tesselate.cpp uses `Vec3d` for `m_output_triangles`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Vec3d {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

impl Vec3d {
    pub fn new(x: f64, y: f64, z: f64) -> Self {
        Self { x, y, z }
    }
    /// `pt.x()` accessor used by the 2D wrappers (Tesselate.cpp:211, 221, 233, 244).
    #[inline]
    pub fn x(&self) -> f64 {
        self.x
    }
    /// `pt.y()` accessor used by the 2D wrappers.
    #[inline]
    pub fn y(&self) -> f64 {
        self.y
    }
}

/// 2D vector with f64 coordinates. Mirrors C++ `Vec2d`.
/// Tesselate.hpp:18
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Vec2d {
    pub x: f64,
    pub y: f64,
}

impl Vec2d {
    pub fn new(x: f64, y: f64) -> Self {
        Self { x, y }
    }
}

/// 2D vector with f32 coordinates. Mirrors C++ `Vec2f`.
/// Tesselate.hpp:20
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Vec2f {
    pub x: f32,
    pub y: f32,
}

impl Vec2f {
    pub fn new(x: f32, y: f32) -> Self {
        Self { x, y }
    }
}

/// Tesselate.hpp:13
pub const NORMALS_UP: bool = false;
/// Tesselate.hpp:14
pub const NORMALS_DOWN: bool = true;

/// GLU primitive types emitted by the tessellator and consumed by the
/// `tessVertex` callback. Mirrors the OpenGL `GLenum` values used in
/// `tessBegin`/`tessVertex` (Tesselate.cpp:112, 134, 146, 149, 152).
#[derive(Clone, Copy, PartialEq, Eq)]
enum GlPrimitive {
    Triangles,
    TriangleFan,
    TriangleStrip,
}

/// 1:1 port of `class GluTessWrapper` (Tesselate.cpp:9-190).
///
/// The native GLU tessellator is replaced by `earcutr`; the callback state
/// machine (`tess_begin` / `tess_end` / `tess_vertex`) is preserved exactly so
/// that the conversion from the primitive stream to output triangles matches
/// C++.
struct GluTessWrapper {
    // Currently processed primitive type. Tesselate.cpp:176
    m_primitive_type: GlPrimitive,
    // Two last vertices received for m_primitive_type. Used for processing triangle strips, fans etc.
    // Tesselate.cpp:178-179
    m_pt0: [f64; 3],
    m_pt1: [f64; 3],
    // Number of points processed over m_primitive_type. Tesselate.cpp:181
    m_num_points: i32,
    // Triangles generated by the tesselator. Tesselate.cpp:183
    m_output_triangles: Vec<Vec3d>,
    // Intersection points generated by tessCombine callback. There should be none if the input contour is not self intersecting.
    // Tesselate.cpp:185
    m_intersection_points: std::collections::VecDeque<Vec3d>,
    // Fixed third coordinate. Tesselate.cpp:187
    m_z: f64,
    // Output triangles shall be flipped (normal points down). Tesselate.cpp:189
    m_flipped: bool,
}

impl GluTessWrapper {
    /// Tesselate.cpp:11-18 (constructor; GLU tessellator + callback registration)
    fn new() -> Self {
        GluTessWrapper {
            m_primitive_type: GlPrimitive::Triangles,
            m_pt0: [0.0; 3],
            m_pt1: [0.0; 3],
            m_num_points: 0,
            m_output_triangles: Vec::new(),
            m_intersection_points: std::collections::VecDeque::new(),
            m_z: 0.0,
            m_flipped: false,
        }
    }

    /// Tesselate.cpp:23-57 (tesselate3d for a single ExPolygon)
    fn tesselate3d_expoly(&mut self, expoly: &ExPolygon, z_: f64, flipped_: bool) -> Vec<Vec3d> {
        self.m_z = z_; // Tesselate.cpp:25
        self.m_flipped = flipped_; // Tesselate.cpp:26
        self.m_output_triangles.clear(); // Tesselate.cpp:27
        // std::vector<GLdouble> coords; (Tesselate.cpp:28) — earcut consumes a
        // flat coordinate buffer directly; the buffer reservation
        // (Tesselate.cpp:29-34) is irrelevant for the earcut backend.

        // gluTessBeginPolygon / gluTessBeginContour for contour (Tesselate.cpp:35-36),
        // contour vertices (Tesselate.cpp:37-42), gluTessEndContour (Tesselate.cpp:43),
        // each hole as its own contour (Tesselate.cpp:44-53),
        // gluTessEndPolygon (Tesselate.cpp:54) — all of this is the GLU input
        // feeding; here it is replaced by an earcut call over the same contour
        // + holes, the resulting triangles are pushed through tess_vertex.
        self.tesselate_one_expoly(expoly);

        self.m_intersection_points.clear(); // Tesselate.cpp:55
        std::mem::take(&mut self.m_output_triangles) // return std::move(m_output_triangles); (Tesselate.cpp:56)
    }

    /// Tesselate.cpp:59-100 (tesselate3d for a vector of ExPolygons)
    fn tesselate3d_expolys(
        &mut self,
        expolygons: &ExPolygons,
        z_: f64,
        flipped_: bool,
    ) -> Vec<Vec3d> {
        self.m_z = z_; // Tesselate.cpp:61
        self.m_flipped = flipped_; // Tesselate.cpp:62
        self.m_output_triangles.clear(); // Tesselate.cpp:63
        // coords buffer sizing (Tesselate.cpp:64-74) is GLU-specific; not needed.

        // for (const ExPolygon &expoly : expolygons) (Tesselate.cpp:75-97):
        // each ExPolygon is tessellated as its own polygon (gluTessBeginPolygon
        // .. gluTessEndPolygon per expoly). Mirror that by triangulating each
        // ExPolygon independently and appending into m_output_triangles.
        for expoly in expolygons {
            self.tesselate_one_expoly(expoly);
        }

        self.m_intersection_points.clear(); // Tesselate.cpp:98
        std::mem::take(&mut self.m_output_triangles) // return std::move(m_output_triangles); (Tesselate.cpp:99)
    }

    /// Triangulate one ExPolygon (contour + holes) with earcut and feed the
    /// resulting triangles through the `tess_vertex` callback as a
    /// `GL_TRIANGLES` primitive stream. This stands in for the GLU input
    /// feeding (Tesselate.cpp:35-54 / 76-96) plus the GLU-driven callbacks.
    fn tesselate_one_expoly(&mut self, expoly: &ExPolygon) {
        // Build the flat coordinate buffer in unscaled mm, contour first then
        // holes, exactly as the GLU vertex feeding does (Tesselate.cpp:37-53):
        //   coords.emplace_back(unscale<double>(pt[0]));
        //   coords.emplace_back(unscale<double>(pt[1]));
        let mut vertices: Vec<f64> = Vec::new();
        let mut hole_indices: Vec<usize> = Vec::new();

        push_polygon_coords(&mut vertices, &expoly.contour); // contour (Tesselate.cpp:37-42)
        for poly in &expoly.holes {
            // gluTessBeginContour per hole (Tesselate.cpp:45). Earcut marks each
            // hole by the vertex index at which it starts.
            hole_indices.push(vertices.len() / 2);
            push_polygon_coords(&mut vertices, poly); // hole vertices (Tesselate.cpp:46-51)
        }

        if vertices.len() < 6 {
            // Fewer than 3 contour vertices: GLU emits no triangles.
            return;
        }

        // earcut triangulation (2D). Returns a flat list of vertex indices,
        // 3 per triangle. This replaces the native GLU tessellator core.
        let indices = match earcutr::earcut(&vertices, &hole_indices, 2) {
            Ok(idx) => idx,
            // tessError is a no-op in C++ (Tesselate.cpp:165-170); on failure we
            // simply emit no triangles for this region.
            Err(_) => {
                self.tess_error();
                return;
            }
        };

        // Feed the triangles through the GLU callback state machine as a
        // GL_TRIANGLES primitive (Tesselate.cpp:110-156).
        self.tess_begin(GlPrimitive::Triangles); // tessBegin (Tesselate.cpp:110-115)
        for tri in indices.chunks_exact(3) {
            for &vi in tri {
                let data = [vertices[vi * 2], vertices[vi * 2 + 1], 0.0];
                self.tess_vertex(Some(&data)); // tessVertex (Tesselate.cpp:122-157)
            }
        }
        self.tess_end(); // tessEnd (Tesselate.cpp:117-120)
    }

    /// Tesselate.cpp:110-115
    fn tess_begin(&mut self, which: GlPrimitive) {
        debug_assert!(matches!(
            which,
            GlPrimitive::Triangles | GlPrimitive::TriangleFan | GlPrimitive::TriangleStrip
        )); // assert(which == GL_TRIANGLES || ...); (Tesselate.cpp:112)
        self.m_primitive_type = which; // Tesselate.cpp:113
        self.m_num_points = 0; // Tesselate.cpp:114
    }

    /// Tesselate.cpp:117-120
    fn tess_end(&mut self) {
        self.m_num_points = 0; // Tesselate.cpp:119
    }

    /// Tesselate.cpp:122-157
    fn tess_vertex(&mut self, data: Option<&[f64; 3]>) {
        let ptr = match data {
            None => return, // if (data == nullptr) return; (Tesselate.cpp:124-125)
            Some(p) => p,   // const GLdouble *ptr = (const GLdouble*)data; (Tesselate.cpp:126)
        };
        self.m_num_points += 1; // ++ m_num_points; (Tesselate.cpp:127)
        if self.m_num_points == 1 {
            self.m_pt0.copy_from_slice(ptr); // memcpy(m_pt0, ptr, sizeof(GLdouble) * 3); (Tesselate.cpp:129)
        } else if self.m_num_points == 2 {
            self.m_pt1.copy_from_slice(ptr); // memcpy(m_pt1, ptr, sizeof(GLdouble) * 3); (Tesselate.cpp:131)
        } else {
            let mut flip = self.m_flipped; // bool flip = m_flipped; (Tesselate.cpp:133)
            if self.m_primitive_type == GlPrimitive::TriangleStrip && self.m_num_points == 4 {
                // Tesselate.cpp:134
                flip = !flip; // Tesselate.cpp:135
                self.m_num_points = 2; // Tesselate.cpp:136
            }
            // m_output_triangles.emplace_back(m_pt0[0], m_pt0[1], m_z); (Tesselate.cpp:138)
            self.m_output_triangles
                .push(Vec3d::new(self.m_pt0[0], self.m_pt0[1], self.m_z));
            if flip {
                // Tesselate.cpp:139-141
                self.m_output_triangles
                    .push(Vec3d::new(ptr[0], ptr[1], self.m_z));
                self.m_output_triangles
                    .push(Vec3d::new(self.m_pt1[0], self.m_pt1[1], self.m_z));
            } else {
                // Tesselate.cpp:142-145
                self.m_output_triangles
                    .push(Vec3d::new(self.m_pt1[0], self.m_pt1[1], self.m_z));
                self.m_output_triangles
                    .push(Vec3d::new(ptr[0], ptr[1], self.m_z));
            }
            if self.m_primitive_type == GlPrimitive::TriangleStrip {
                // Tesselate.cpp:146
                self.m_pt0 = self.m_pt1; // memcpy(m_pt0, m_pt1, sizeof(GLdouble) * 3); (Tesselate.cpp:147)
                self.m_pt1.copy_from_slice(ptr); // memcpy(m_pt1, ptr, sizeof(GLdouble) * 3); (Tesselate.cpp:148)
            } else if self.m_primitive_type == GlPrimitive::TriangleFan {
                // Tesselate.cpp:149
                self.m_pt1.copy_from_slice(ptr); // memcpy(m_pt1, ptr, sizeof(GLdouble) * 3); (Tesselate.cpp:150)
            } else {
                debug_assert!(self.m_primitive_type == GlPrimitive::Triangles); // assert (Tesselate.cpp:152)
                debug_assert!(self.m_num_points == 3); // assert (Tesselate.cpp:153)
                self.m_num_points = 0; // Tesselate.cpp:154
            }
        }
    }

    /// Tesselate.cpp:159-163 (tessCombine)
    ///
    /// Records an intersection vertex created by the tessellator at a
    /// self-intersection. The earcut backend does not split self-intersections,
    /// so this is retained for fidelity but is not exercised by that backend.
    #[allow(dead_code)]
    fn tess_combine(&mut self, new_vertex: &[f64; 3]) -> *const f64 {
        // m_intersection_points.emplace_back(newVertex[0], newVertex[1], m_z); (Tesselate.cpp:161)
        self.m_intersection_points
            .push_back(Vec3d::new(new_vertex[0], new_vertex[1], self.m_z));
        // *outData = m_intersection_points.back().data(); (Tesselate.cpp:162)
        let back = self.m_intersection_points.back().unwrap();
        &back.x as *const f64
    }

    /// Tesselate.cpp:165-170 (tessError) — no-op (error string printing is
    /// commented out in C++).
    fn tess_error(&self) {
        // const GLubyte *errorStr; (Tesselate.cpp:167)
        // errorStr = gluErrorString(errorCode); (Tesselate.cpp:168)
        // printf("Error: %s\n", (const char*)errorStr); (Tesselate.cpp:169)
    }
}

/// Append a polygon's vertices (unscaled mm) to a flat earcut coordinate
/// buffer. Mirrors the per-vertex feeding loop (Tesselate.cpp:37-42 / 46-51):
///   coords.emplace_back(unscale<double>(pt[0]));
///   coords.emplace_back(unscale<double>(pt[1]));
fn push_polygon_coords(vertices: &mut Vec<f64>, poly: &Polygon) {
    for pt in &poly.points {
        vertices.push(unscale(pt.x)); // unscale<double>(pt[0]) (Tesselate.cpp:38)
        vertices.push(unscale(pt.y)); // unscale<double>(pt[1]) (Tesselate.cpp:39)
    }
}

/// Tesselate.cpp:192-196
pub fn triangulate_expolygon_3d(poly: &ExPolygon, z: f64, flip: bool) -> Result<Vec<Vec3d>> {
    let mut tess = GluTessWrapper::new(); // GluTessWrapper tess; (Tesselate.cpp:194)
    Ok(tess.tesselate3d_expoly(poly, z, flip)) // return tess.tesselate3d(poly, z, flip); (Tesselate.cpp:195)
}

/// Tesselate.cpp:198-202
pub fn triangulate_expolygons_3d(polys: &ExPolygons, z: f64, flip: bool) -> Result<Vec<Vec3d>> {
    let mut tess = GluTessWrapper::new(); // GluTessWrapper tess; (Tesselate.cpp:200)
    Ok(tess.tesselate3d_expolys(polys, z, flip)) // return tess.tesselate3d(polys, z, flip); (Tesselate.cpp:201)
}

/// Tesselate.cpp:204-213
pub fn triangulate_expolygon_2d(poly: &ExPolygon, flip: bool) -> Result<Vec<Vec2d>> {
    let mut tess = GluTessWrapper::new(); // GluTessWrapper tess; (Tesselate.cpp:206)
    let triangles = tess.tesselate3d_expoly(poly, 0.0, flip); // (Tesselate.cpp:207)
    let mut out: Vec<Vec2d> = Vec::with_capacity(triangles.len()); // out.reserve(triangles.size()); (Tesselate.cpp:208-209)
    for pt in &triangles {
        // for (const Vec3d &pt : triangles) (Tesselate.cpp:210)
        out.push(Vec2d::new(pt.x(), pt.y())); // out.emplace_back(pt.x(), pt.y()); (Tesselate.cpp:211)
    }
    Ok(out) // return out; (Tesselate.cpp:212)
}

/// Tesselate.cpp:215-224
pub fn triangulate_expolygons_2d(polys: &ExPolygons, flip: bool) -> Result<Vec<Vec2d>> {
    let mut tess = GluTessWrapper::new(); // GluTessWrapper tess; (Tesselate.cpp:217)
    let triangles = tess.tesselate3d_expolys(polys, 0.0, flip); // (Tesselate.cpp:218)
    let mut out: Vec<Vec2d> = Vec::with_capacity(triangles.len()); // out.reserve(triangles.size()); (Tesselate.cpp:219-220)
    for pt in &triangles {
        // for (const Vec3d &pt : triangles) (Tesselate.cpp:221)
        out.push(Vec2d::new(pt.x(), pt.y())); // out.emplace_back(pt.x(), pt.y()); (Tesselate.cpp:222)
    }
    Ok(out) // return out; (Tesselate.cpp:223)
}

/// Tesselate.cpp:226-235
pub fn triangulate_expolygon_2f(poly: &ExPolygon, flip: bool) -> Result<Vec<Vec2f>> {
    let mut tess = GluTessWrapper::new(); // GluTessWrapper tess; (Tesselate.cpp:228)
    let triangles = tess.tesselate3d_expoly(poly, 0.0, flip); // (Tesselate.cpp:229)
    let mut out: Vec<Vec2f> = Vec::with_capacity(triangles.len()); // out.reserve(triangles.size()); (Tesselate.cpp:230-231)
    for pt in &triangles {
        // for (const Vec3d &pt : triangles) (Tesselate.cpp:232)
        out.push(Vec2f::new(pt.x() as f32, pt.y() as f32)); // out.emplace_back(float(pt.x()), float(pt.y())); (Tesselate.cpp:233)
    }
    Ok(out) // return out; (Tesselate.cpp:234)
}

/// Tesselate.cpp:237-246
pub fn triangulate_expolygons_2f(polys: &ExPolygons, flip: bool) -> Result<Vec<Vec2f>> {
    let mut tess = GluTessWrapper::new(); // GluTessWrapper tess; (Tesselate.cpp:239)
    let triangles = tess.tesselate3d_expolys(polys, 0.0, flip); // (Tesselate.cpp:240)
    let mut out: Vec<Vec2f> = Vec::with_capacity(triangles.len()); // out.reserve(triangles.size()); (Tesselate.cpp:241-242)
    for pt in &triangles {
        // for (const Vec3d &pt : triangles) (Tesselate.cpp:243)
        out.push(Vec2f::new(pt.x() as f32, pt.y() as f32)); // out.emplace_back(float(pt.x()), float(pt.y())); (Tesselate.cpp:244)
    }
    Ok(out) // return out; (Tesselate.cpp:245)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::{Point, Polygon};

    fn unit_square() -> ExPolygon {
        // 10mm x 10mm square (scaled coords).
        let s = crate::scale(10.0);
        ExPolygon::new(Polygon::new(vec![
            Point::new(0, 0),
            Point::new(s, 0),
            Point::new(s, s),
            Point::new(0, s),
        ]))
    }

    #[test]
    fn test_vec3d_creation() {
        let v = Vec3d::new(1.0, 2.0, 3.0);
        assert_eq!(v.x, 1.0);
        assert_eq!(v.y, 2.0);
        assert_eq!(v.z, 3.0);
    }

    #[test]
    fn test_normals_constants() {
        assert_eq!(NORMALS_UP, false);
        assert_eq!(NORMALS_DOWN, true);
    }

    #[test]
    fn test_triangulate_square_3d() {
        let poly = unit_square();
        let tris = triangulate_expolygon_3d(&poly, 5.0, NORMALS_UP).unwrap();
        // A quad triangulates into 2 triangles = 6 vertices.
        assert_eq!(tris.len(), 6);
        // All vertices at the requested Z.
        for v in &tris {
            assert!((v.z - 5.0).abs() < 1e-9);
        }
    }

    #[test]
    fn test_triangulate_square_2d_and_2f() {
        let poly = unit_square();
        let d = triangulate_expolygon_2d(&poly, NORMALS_UP).unwrap();
        let f = triangulate_expolygon_2f(&poly, NORMALS_UP).unwrap();
        assert_eq!(d.len(), 6);
        assert_eq!(f.len(), 6);
        for (vd, vf) in d.iter().zip(f.iter()) {
            assert!((vd.x - vf.x as f64).abs() < 1e-6);
            assert!((vd.y - vf.y as f64).abs() < 1e-6);
        }
    }

    #[test]
    fn test_flip_reverses_winding() {
        let poly = unit_square();
        let up = triangulate_expolygon_2d(&poly, NORMALS_UP).unwrap();
        let down = triangulate_expolygon_2d(&poly, NORMALS_DOWN).unwrap();
        assert_eq!(up.len(), down.len());
        // For each triangle, NORMALS_DOWN swaps vertices 1 and 2 (Tesselate.cpp:139-145).
        for tri in 0..(up.len() / 3) {
            let i = tri * 3;
            assert_eq!(up[i], down[i]); // pt0 unchanged
            assert_eq!(up[i + 1], down[i + 2]);
            assert_eq!(up[i + 2], down[i + 1]);
        }
    }

    #[test]
    fn test_empty_expolygons() {
        let polys: ExPolygons = ExPolygons::new();
        let tris = triangulate_expolygons_3d(&polys, 0.0, NORMALS_UP).unwrap();
        assert_eq!(tris.len(), 0);
    }

    #[test]
    fn test_degenerate_returns_empty() {
        // Fewer than 3 vertices -> no triangles.
        let poly = ExPolygon::new(Polygon::new(vec![Point::new(0, 0), Point::new(100, 0)]));
        let tris = triangulate_expolygon_3d(&poly, 0.0, NORMALS_UP).unwrap();
        assert_eq!(tris.len(), 0);
    }
}
